# Generated by Django 3.0 on 2021-11-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cxname', models.CharField(max_length=50)),
                ('cxemail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
