# Generated by Django 3.0 on 2021-11-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_orders_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='zip_code',
        ),
    ]
