# Generated by Django 2.2.10 on 2021-10-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prtype', models.CharField(max_length=5000)),
                ('prprice', models.IntegerField(default=50)),
                ('prname', models.CharField(max_length=5000)),
                ('prdesc', models.CharField(max_length=5000)),
                ('primage', models.ImageField(default='', upload_to='image/')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
