# Generated by Django 2.2.10 on 2021-11-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_time',
            new_name='prdate_time',
        ),
    ]
