# Generated by Django 3.0 on 2021-11-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_prqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prqty',
            field=models.IntegerField(default=50),
        ),
    ]
